[pytest]
; addopts = --headed --capture=tee-sys --html=reports/report.html
markers =
    login: marks tests as login tests
    smoke: marks tests as smoke tests
    regression: marks tests as regression tests